name: pulseaudio
version: 8.0-1
summary: Audio framework (contains PulseAudio and alsa-lib)
description: Contains PulseAudio and its dependencies, to
  enable apps to play back and record sound by talking to
  PulseAudio.
  Please find the source code at https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/pulseaudio

slots:
  service: pulseaudio
plugs:
  client: pulseaudio

apps:
  pulseaudio:
    command: bin/pulseaudio
    daemon: simple
    slots: [service]
  pactl:
    command: bin/pactl
    plugs: [client]
  paplay:
    command: bin/paplay
    plugs: [client]
  parec:
    command: bin/parec
    plugs: [client]

parts:
  pulseaudio-common:
    plugin: copy
    files:
      bin/pulseaudio: bin/pulseaudio
      bin/pactl: bin/pactl
      bin/paplay: bin/paplay
      bin/parec: bin/parec

  pulseaudio:
    plugin: autotools

    source: http://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-8.0.tar.xz

    # NOTE: Force autogen to be executed again even if the tarball already
    # comes with a configure script but that links against aclocal-1.13
    # which we don't profile anymore and will cause the build to fail.
    force-autogen: true

    build-packages:
      - intltool
      - libasound2-dev
      - libdbus-1-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libspeexdsp-dev
      - libbluetooth-dev
      - libwebrtc-audio-processing-dev
      - libltdl-dev
      - libsndfile1-dev
      - libx11-xcb-dev
      - libx11-dev
      - libtdb-dev
      - libudev-dev
      - libasyncns-dev
      - libxcb1-dev

    stage-packages:
      # Needed for various ALSA related configuration files the alsa
      # module inside PulseAudio requires to use any available audio
      # device properly
      - libasound2-data

    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --enable-udev
      - --disable-rpath
      - --disable-orc
      - --disable-gconf
      - --disable-bluez4
      - --disable-bluez5
      - --disable-esound
      - --disable-adrian-aec
      - --disable-gtk3
      - --disable-hal-compat
      - --disable-systemd-login
      - --without-caps
      - --disable-webrtc-aec
      - --disable-dbus
      - --disable-oss-output
      - --disable-oss-wrapper
      - --disable-jack
      - --disable-x11
      - --with-system-user=root
      - --with-system-group=root
